FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y \
    curl \
    wget \
    mc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    mlflow==2.8.1 \
    psycopg2-binary \
    boto3 \
    pymysql

EXPOSE 5001

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl --fail http://localhost:5001/health || exit 1